spring:
  application:
  name: batch-processing


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    job:
      enabled: false

